// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/list-deals.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-deals.ts
var DEAL_FIELDS = "id, homeowner1, homeowner2, address, stage, products, lead_source, price_a, price_b, price_c, closed_amount, closed_at, install_date, notes, updated_at, created_at";
var list_deals_default = defineTool({
  name: "list_deals",
  title: "List deals",
  description: "List the signed-in rep's deals, newest first. Optionally filter by pipeline stage or search homeowner name / address.",
  inputSchema: {
    stage: z.enum(["inspecting", "presented", "follow_up", "won", "lost", "disqualified"]).optional().describe("Only return deals in this pipeline stage."),
    search: z.string().optional().describe("Case-insensitive match on homeowner name or address."),
    limit: z.number().int().optional().describe("Max deals to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ stage, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const capped = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabase.from("deals").select(DEAL_FIELDS).order("updated_at", { ascending: false }).limit(capped);
    if (stage) query = query.eq("stage", stage);
    if (search?.trim()) {
      const term = `%${search.trim()}%`;
      query = query.or(
        `homeowner1.ilike.${term},homeowner2.ilike.${term},address.ilike.${term}`
      );
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { deals: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-deal.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_deal_default = defineTool2({
  name: "get_deal",
  title: "Get deal",
  description: "Fetch one deal by id with its pricing, stage history and open follow-ups. Only returns deals owned by the signed-in rep.",
  inputSchema: { deal_id: z2.string().describe("The deal id (uuid).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ deal_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: deal, error } = await supabase.from("deals").select("*").eq("id", deal_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!deal) return { content: [{ type: "text", text: "Deal not found" }], isError: true };
    const [{ data: history }, { data: followUps }] = await Promise.all([
      supabase.from("deal_stage_history").select("*").eq("deal_id", deal_id).order("created_at", { ascending: false }).limit(20),
      supabase.from("follow_ups").select("id, due_at, touchpoint_number, channel, notes, completed_at").eq("deal_id", deal_id).order("due_at", { ascending: true }).limit(20)
    ]);
    const payload = { deal, stage_history: history ?? [], follow_ups: followUps ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/create-deal.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^3.25.76";
var create_deal_default = defineTool3({
  name: "create_deal",
  title: "Create deal",
  description: "Create a new deal (lead) owned by the signed-in rep.",
  inputSchema: {
    homeowner1: z3.string().describe("Primary homeowner name."),
    homeowner2: z3.string().optional().describe("Second homeowner name, if any."),
    address: z3.string().optional().describe("Property address."),
    homeowner_email: z3.string().optional(),
    homeowner_phone: z3.string().optional(),
    lead_source: z3.string().optional().describe("Where the lead came from, e.g. canvass, referral."),
    products: z3.array(z3.string()).optional().describe("Product lines in play, e.g. roofing, windows, siding, bath, cool life."),
    notes: z3.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("deals").insert({ ...input, rep_id: ctx.getUserId(), stage: "inspecting" }).select("id, homeowner1, homeowner2, address, stage, products, lead_source, created_at").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { deal: data }
    };
  }
});

// src/lib/mcp/tools/update-deal.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z4 } from "npm:zod@^3.25.76";
var update_deal_default = defineTool4({
  name: "update_deal",
  title: "Update deal",
  description: "Update a deal owned by the signed-in rep: move its pipeline stage, set option pricing, closed amount, install date or notes.",
  inputSchema: {
    deal_id: z4.string().describe("The deal id (uuid)."),
    stage: z4.enum(["inspecting", "presented", "follow_up", "won", "lost", "disqualified"]).optional(),
    notes: z4.string().optional(),
    address: z4.string().optional(),
    lead_source: z4.string().optional(),
    price_a: z4.number().optional().describe("Good option price."),
    price_b: z4.number().optional().describe("Better option price."),
    price_c: z4.number().optional().describe("Best option price."),
    closed_amount: z4.number().optional().describe("Contract amount when the deal is won."),
    install_date: z4.string().optional().describe("Install date as YYYY-MM-DD."),
    lost_reason: z4.string().optional(),
    disqualified_reason: z4.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ deal_id, ...patch }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const updates = Object.fromEntries(
      Object.entries(patch).filter(([, v]) => v !== void 0)
    );
    if (Object.keys(updates).length === 0) {
      return { content: [{ type: "text", text: "No fields to update" }], isError: true };
    }
    if (updates.stage) updates.stage_changed_at = (/* @__PURE__ */ new Date()).toISOString();
    if (updates.stage === "won" && !updates.closed_at) updates.closed_at = (/* @__PURE__ */ new Date()).toISOString();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("deals").update(updates).eq("id", deal_id).select("id, homeowner1, address, stage, price_a, price_b, price_c, closed_amount, install_date, notes, updated_at").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Deal not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { deal: data }
    };
  }
});

// src/lib/mcp/tools/pipeline-summary.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z5 } from "npm:zod@^3.25.76";
var pipeline_summary_default = defineTool5({
  name: "pipeline_summary",
  title: "Pipeline summary",
  description: "Summarize the signed-in rep's pipeline: deal counts by stage, won revenue and open pipeline value over a recent window.",
  inputSchema: {
    days: z5.number().int().optional().describe("Look-back window in days (default 90, max 730).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const window = Math.min(Math.max(days ?? 90, 1), 730);
    const since = new Date(Date.now() - window * 864e5).toISOString();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("deals").select("stage, closed_amount, price_c, created_at").gte("created_at", since);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const byStage = {};
    let wonRevenue = 0;
    let openValue = 0;
    for (const row of rows) {
      byStage[row.stage] = (byStage[row.stage] ?? 0) + 1;
      if (row.stage === "won") wonRevenue += Number(row.closed_amount ?? 0);
      else if (["inspecting", "presented", "follow_up"].includes(row.stage)) {
        openValue += Number(row.price_c ?? 0);
      }
    }
    const decided = (byStage.won ?? 0) + (byStage.lost ?? 0);
    const summary = {
      window_days: window,
      total_deals: rows.length,
      by_stage: byStage,
      won_revenue: wonRevenue,
      open_pipeline_value: openValue,
      close_rate: decided > 0 ? Number(((byStage.won ?? 0) / decided).toFixed(3)) : null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-follow-ups.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z6 } from "npm:zod@^3.25.76";
var list_follow_ups_default = defineTool6({
  name: "list_follow_ups",
  title: "List follow-ups",
  description: "List the signed-in rep's follow-up touchpoints, soonest first. Defaults to open (not completed) follow-ups.",
  inputSchema: {
    include_completed: z6.boolean().optional().describe("Include completed follow-ups too."),
    due_within_days: z6.number().int().optional().describe("Only follow-ups due within this many days from now."),
    limit: z6.number().int().optional().describe("Max rows to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_completed, due_within_days, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const capped = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabase.from("follow_ups").select("id, deal_id, due_at, touchpoint_number, channel, notes, context_notes, completed_at").order("due_at", { ascending: true }).limit(capped);
    if (!include_completed) query = query.is("completed_at", null);
    if (due_within_days !== void 0) {
      const until = new Date(Date.now() + Math.max(due_within_days, 0) * 864e5).toISOString();
      query = query.lte("due_at", until);
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { follow_ups: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nchwcadaoqhlrmbdzzrt";
var mcp_default = defineMcp({
  name: "dabella-close-assist",
  title: "DaBella Close Assist",
  version: "0.1.0",
  instructions: "Tools for the DaBella Close Engine sales app. Every tool acts as the signed-in rep. Use `list_deals` and `get_deal` to read the rep's pipeline, `create_deal` and `update_deal` to add leads or move stages, `pipeline_summary` for stage counts, won revenue and close rate, and `list_follow_ups` for upcoming touchpoints.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_deals_default,
    get_deal_default,
    create_deal_default,
    update_deal_default,
    pipeline_summary_default,
    list_follow_ups_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
