ALTER TABLE public.deals
  ADD COLUMN IF NOT EXISTS lead_source TEXT,
  ADD COLUMN IF NOT EXISTS was_presented BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS was_demoed BOOLEAN NOT NULL DEFAULT false;